name: Update page
on:
  push:
    branches:
      - main

jobs:

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Collect entries and sections
        run: |
          echo "entries=$(grep -ioR '^## ' * | wc -l)" >> $GITHUB_ENV
          echo "sections=$(grep -ioR '^# ' * | wc -l)" >> $GITHUB_ENV

      - name: Replace Tokens in readme.md
        uses: cschleiden/replace-tokens@master
        with:
          files: 'README.md'
        env:
          entries: entries
          sections: sections
        
      - name: Put readme.md as index.md
        run:  cp ./README.md docs/index.md

      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}